language: node_js
node_js:
- "8"
script:
- npm run lint
- npm test

notifications:
  email:
    recipients:
      - pfranco@outlook.com
    on_success: always 
    on_failure: always
deploy:
  provider: npm
  email: "pfranco@outlook.com"
  api_key: "tN6E2BjUGznMRs7AfEg6u1XwmqeVx9/0kokUidQndjLPy8nVav/aU4w06IhQfhpu97j5jfoPVjpFEFb8xIqDpAWbIXq8qnHxf3uZ5VyYTASh5jAbg/CLCBWsyzcfsNNB/Hzymqi5QpQfhQObsS9KVLLfiU9GgIAszv+Rd6YSgNRFJd2yVAinLzRgPelMo50PNbgsfoO/2ATnGw/AvuvMwCRCx/5vjBbpqzKo5a+Ms7fd3ZBOylZNPnbpPrpFemuipe/rsb2Uz2YYSaA6Zko75AekOHYsI8wjUaf7jeF1TRQmhBFcQDDrVd71EwXXTXMVSp99SBDiKh/8KicALxxf/whPvvnI9spR1EFoZGVl7z0fZKpBqqVvDJwKr0vz6rBqApTx8HLOW0598hwyMXRBGcaQ20V/j1BR3vzCXKKtnarBLFBPBWBLUvNFY6EQYG/kI7ZldggoOEB/gfN4CEYjOZ2DzcWGHGM7FAQrr+6xv/OoeMhEPCzwdRnm1k3ymNCnrS/g+OTAKxtUV86lBQgMf/YGD7jcjv8ZHj059wO2CwzWDU+BfRQuqJMAqNuORr8frPkypT7kqKoR+0WH8zutmq0P8GMpwIz0v6BHIoHKhbVNfaSWmoA3Xmbpz64u0GelImfXBqqhTK+GW3YV+nHAS2EBvtRiVoSYVoyr52CBH3A="
  skip_cleanup: true
  on:
    tags: true
