language: node_js
node_js:
- "8"
script:
- npm run lint
- npm test

notifications:
  email:
    recipients:
      - pfranco@outlook.com
    on_success: always 
    on_failure: always
deploy:
  provider: npm
  email: "pfranco@outlook.com"
  api_key: "DH2g3d4JqELc7BPKFkA/z+g42Po1c7onQ49fYHSuhs5JJ/V4iyZNQwTa81Wv7ByoNA5WMsZq56ZEAijURRLpjmxqa5m6KoHj6dTKSw5pD8NxAJniGqwc0h3MVmTIrS5INlHr1+mHw5TfzVfsvqCy6kmqMo1P4KioYTcREVRttfNv0zGnWxzrN8kvXKafiTpqLJhiDgB/KcqIXHh6OjM9PlQk/La6UwFU8SPcXt/wmw+Y6zy2kiUJtwNQRawMOGOvjn9ZUN+uZg3qD6TiBVdmm+2BoiCM3qAN5ZyFYSIREov4XOBhcSt74aKoOMyo8TY3pyyyN85uzO47n1vZ6CJ1vSvOxOtTz+tI4rfGezXacJ20PXUYLzFOcpegktWAxzobn/UAXcOn8WnxikRD9uGYsNqk4rP7noHQdIU3lRnhq9ch/oO3u9VQRHU9nTn6DlDVMG57EdTlsNweDEZWpHkpBN8QwJFWA2sw+PYawSzS4AnSnpqdPyIcEruVZMW+aMDT4T4ObOV9kV3i6kBlfcHmj2GSMf1RE2C+hN9JGY2Tss4Wn5TMM6t0+RU+mrNvDpPfEeiq5wPNsYlXIULMkNO7/oqvZuAHgXv/6WkmZuQlGGigLs3u+4l4bujzm06uymXNkV59ujPYTXMdYGYRw98/I6UytrErnmnx3I00o8TQKNM="
  skip_cleanup: true
  on:
    branch: master
    tags: true